// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	pkgtypes "github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/types"
	mock "github.com/stretchr/testify/mock"
	types "k8s.io/apimachinery/pkg/types"
)

// MockPreparedClaimStore is an autogenerated mock type for the PreparedClaimStore type
type MockPreparedClaimStore struct {
	mock.Mock
}

type MockPreparedClaimStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPreparedClaimStore) EXPECT() *MockPreparedClaimStore_Expecter {
	return &MockPreparedClaimStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockPreparedClaimStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPreparedClaimStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPreparedClaimStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPreparedClaimStore_Expecter) Close() *MockPreparedClaimStore_Close_Call {
	return &MockPreparedClaimStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPreparedClaimStore_Close_Call) Run(run func()) *MockPreparedClaimStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPreparedClaimStore_Close_Call) Return(_a0 error) *MockPreparedClaimStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPreparedClaimStore_Close_Call) RunAndReturn(run func() error) *MockPreparedClaimStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: claimUID
func (_m *MockPreparedClaimStore) Delete(claimUID types.UID) error {
	ret := _m.Called(claimUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UID) error); ok {
		r0 = rf(claimUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPreparedClaimStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPreparedClaimStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - claimUID types.UID
func (_e *MockPreparedClaimStore_Expecter) Delete(claimUID interface{}) *MockPreparedClaimStore_Delete_Call {
	return &MockPreparedClaimStore_Delete_Call{Call: _e.mock.On("Delete", claimUID)}
}

func (_c *MockPreparedClaimStore_Delete_Call) Run(run func(claimUID types.UID)) *MockPreparedClaimStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID))
	})
	return _c
}

func (_c *MockPreparedClaimStore_Delete_Call) Return(_a0 error) *MockPreparedClaimStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPreparedClaimStore_Delete_Call) RunAndReturn(run func(types.UID) error) *MockPreparedClaimStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: claimUID
func (_m *MockPreparedClaimStore) Get(claimUID types.UID) ([]*pkgtypes.PreparedDevice, error) {
	ret := _m.Called(claimUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*pkgtypes.PreparedDevice
	var r1 error
	if rf, ok := ret.Get(0).(func(types.UID) ([]*pkgtypes.PreparedDevice, error)); ok {
		return rf(claimUID)
	}
	if rf, ok := ret.Get(0).(func(types.UID) []*pkgtypes.PreparedDevice); ok {
		r0 = rf(claimUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pkgtypes.PreparedDevice)
		}
	}

	if rf, ok := ret.Get(1).(func(types.UID) error); ok {
		r1 = rf(claimUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPreparedClaimStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPreparedClaimStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - claimUID types.UID
func (_e *MockPreparedClaimStore_Expecter) Get(claimUID interface{}) *MockPreparedClaimStore_Get_Call {
	return &MockPreparedClaimStore_Get_Call{Call: _e.mock.On("Get", claimUID)}
}

func (_c *MockPreparedClaimStore_Get_Call) Run(run func(claimUID types.UID)) *MockPreparedClaimStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID))
	})
	return _c
}

func (_c *MockPreparedClaimStore_Get_Call) Return(_a0 []*pkgtypes.PreparedDevice, _a1 error) *MockPreparedClaimStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPreparedClaimStore_Get_Call) RunAndReturn(run func(types.UID) ([]*pkgtypes.PreparedDevice, error)) *MockPreparedClaimStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: claimUID, sc
func (_m *MockPreparedClaimStore) Set(claimUID types.UID, sc []*pkgtypes.PreparedDevice) error {
	ret := _m.Called(claimUID, sc)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UID, []*pkgtypes.PreparedDevice) error); ok {
		r0 = rf(claimUID, sc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPreparedClaimStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockPreparedClaimStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - claimUID types.UID
//   - sc []*pkgtypes.PreparedDevice
func (_e *MockPreparedClaimStore_Expecter) Set(claimUID interface{}, sc interface{}) *MockPreparedClaimStore_Set_Call {
	return &MockPreparedClaimStore_Set_Call{Call: _e.mock.On("Set", claimUID, sc)}
}

func (_c *MockPreparedClaimStore_Set_Call) Run(run func(claimUID types.UID, sc []*pkgtypes.PreparedDevice)) *MockPreparedClaimStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID), args[1].([]*pkgtypes.PreparedDevice))
	})
	return _c
}

func (_c *MockPreparedClaimStore_Set_Call) Return(_a0 error) *MockPreparedClaimStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPreparedClaimStore_Set_Call) RunAndReturn(run func(types.UID, []*pkgtypes.PreparedDevice) error) *MockPreparedClaimStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPreparedClaimStore creates a new instance of MockPreparedClaimStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPreparedClaimStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPreparedClaimStore {
	mock := &MockPreparedClaimStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
