with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/socketfs:
    config:
      dir: "pkg/socketfs/mocks"
      outpkg: "mocks"
    interfaces:
      SocketFS:
  github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/ovs:
    config:
      dir: "pkg/ovs/mocks"
      outpkg: "mocks"
    interfaces:
      Client:
  github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/devicestate:
    config:
      dir: "pkg/devicestate/mocks"
      outpkg: "mocks"
    interfaces:
      DeviceStateIface:
  github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/deviceplugin:
    config:
      dir: "pkg/deviceplugin/mocks"
      outpkg: "mocks"
    interfaces:
      TopologyDPServer:
