// Code generated by mockery. DO NOT EDIT.

package dp

import mock "github.com/stretchr/testify/mock"

// MocknumaProvider is an autogenerated mock type for the numaProvider type
type MocknumaProvider struct {
	mock.Mock
}

type MocknumaProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MocknumaProvider) EXPECT() *MocknumaProvider_Expecter {
	return &MocknumaProvider_Expecter{mock: &_m.Mock}
}

// BridgeNUMANodes provides a mock function with given fields: bridgeName
func (_m *MocknumaProvider) BridgeNUMANodes(bridgeName string) []int {
	ret := _m.Called(bridgeName)

	if len(ret) == 0 {
		panic("no return value specified for BridgeNUMANodes")
	}

	var r0 []int
	if rf, ok := ret.Get(0).(func(string) []int); ok {
		r0 = rf(bridgeName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// MocknumaProvider_BridgeNUMANodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BridgeNUMANodes'
type MocknumaProvider_BridgeNUMANodes_Call struct {
	*mock.Call
}

// BridgeNUMANodes is a helper method to define mock.On call
//   - bridgeName string
func (_e *MocknumaProvider_Expecter) BridgeNUMANodes(bridgeName interface{}) *MocknumaProvider_BridgeNUMANodes_Call {
	return &MocknumaProvider_BridgeNUMANodes_Call{Call: _e.mock.On("BridgeNUMANodes", bridgeName)}
}

func (_c *MocknumaProvider_BridgeNUMANodes_Call) Run(run func(bridgeName string)) *MocknumaProvider_BridgeNUMANodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MocknumaProvider_BridgeNUMANodes_Call) Return(_a0 []int) *MocknumaProvider_BridgeNUMANodes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocknumaProvider_BridgeNUMANodes_Call) RunAndReturn(run func(string) []int) *MocknumaProvider_BridgeNUMANodes_Call {
	_c.Call.Return(run)
	return _c
}

// SetInterfaceNotifier provides a mock function with given fields: fn
func (_m *MocknumaProvider) SetInterfaceNotifier(fn func(string)) {
	_m.Called(fn)
}

// MocknumaProvider_SetInterfaceNotifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInterfaceNotifier'
type MocknumaProvider_SetInterfaceNotifier_Call struct {
	*mock.Call
}

// SetInterfaceNotifier is a helper method to define mock.On call
//   - fn func(string)
func (_e *MocknumaProvider_Expecter) SetInterfaceNotifier(fn interface{}) *MocknumaProvider_SetInterfaceNotifier_Call {
	return &MocknumaProvider_SetInterfaceNotifier_Call{Call: _e.mock.On("SetInterfaceNotifier", fn)}
}

func (_c *MocknumaProvider_SetInterfaceNotifier_Call) Run(run func(fn func(string))) *MocknumaProvider_SetInterfaceNotifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string)))
	})
	return _c
}

func (_c *MocknumaProvider_SetInterfaceNotifier_Call) Return() *MocknumaProvider_SetInterfaceNotifier_Call {
	_c.Call.Return()
	return _c
}

func (_c *MocknumaProvider_SetInterfaceNotifier_Call) RunAndReturn(run func(func(string))) *MocknumaProvider_SetInterfaceNotifier_Call {
	_c.Run(run)
	return _c
}

// NewMocknumaProvider creates a new instance of MocknumaProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocknumaProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocknumaProvider {
	mock := &MocknumaProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
