// Code generated by mockery. DO NOT EDIT.

package dp

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTopologyDPServer is an autogenerated mock type for the TopologyDPServer type
type MockTopologyDPServer struct {
	mock.Mock
}

type MockTopologyDPServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopologyDPServer) EXPECT() *MockTopologyDPServer_Expecter {
	return &MockTopologyDPServer_Expecter{mock: &_m.Mock}
}

// GetNUMA provides a mock function with no fields
func (_m *MockTopologyDPServer) GetNUMA() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNUMA")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTopologyDPServer_GetNUMA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNUMA'
type MockTopologyDPServer_GetNUMA_Call struct {
	*mock.Call
}

// GetNUMA is a helper method to define mock.On call
func (_e *MockTopologyDPServer_Expecter) GetNUMA() *MockTopologyDPServer_GetNUMA_Call {
	return &MockTopologyDPServer_GetNUMA_Call{Call: _e.mock.On("GetNUMA")}
}

func (_c *MockTopologyDPServer_GetNUMA_Call) Run(run func()) *MockTopologyDPServer_GetNUMA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTopologyDPServer_GetNUMA_Call) Return(_a0 int) *MockTopologyDPServer_GetNUMA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopologyDPServer_GetNUMA_Call) RunAndReturn(run func() int) *MockTopologyDPServer_GetNUMA_Call {
	_c.Call.Return(run)
	return _c
}

// start provides a mock function with given fields: ctx
func (_m *MockTopologyDPServer) start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTopologyDPServer_start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'start'
type MockTopologyDPServer_start_Call struct {
	*mock.Call
}

// start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTopologyDPServer_Expecter) start(ctx interface{}) *MockTopologyDPServer_start_Call {
	return &MockTopologyDPServer_start_Call{Call: _e.mock.On("start", ctx)}
}

func (_c *MockTopologyDPServer_start_Call) Run(run func(ctx context.Context)) *MockTopologyDPServer_start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTopologyDPServer_start_Call) Return(_a0 error) *MockTopologyDPServer_start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopologyDPServer_start_Call) RunAndReturn(run func(context.Context) error) *MockTopologyDPServer_start_Call {
	_c.Call.Return(run)
	return _c
}

// stop provides a mock function with no fields
func (_m *MockTopologyDPServer) stop() {
	_m.Called()
}

// MockTopologyDPServer_stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'stop'
type MockTopologyDPServer_stop_Call struct {
	*mock.Call
}

// stop is a helper method to define mock.On call
func (_e *MockTopologyDPServer_Expecter) stop() *MockTopologyDPServer_stop_Call {
	return &MockTopologyDPServer_stop_Call{Call: _e.mock.On("stop")}
}

func (_c *MockTopologyDPServer_stop_Call) Run(run func()) *MockTopologyDPServer_stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTopologyDPServer_stop_Call) Return() *MockTopologyDPServer_stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTopologyDPServer_stop_Call) RunAndReturn(run func()) *MockTopologyDPServer_stop_Call {
	_c.Run(run)
	return _c
}

// NewMockTopologyDPServer creates a new instance of MockTopologyDPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopologyDPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopologyDPServer {
	mock := &MockTopologyDPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
