// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTopologyDPServer is an autogenerated mock type for the TopologyDPServer type
type MockTopologyDPServer struct {
	mock.Mock
}

type MockTopologyDPServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopologyDPServer) EXPECT() *MockTopologyDPServer_Expecter {
	return &MockTopologyDPServer_Expecter{mock: &_m.Mock}
}

// GetNUMA provides a mock function with no fields
func (_m *MockTopologyDPServer) GetNUMA() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNUMA")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTopologyDPServer_GetNUMA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNUMA'
type MockTopologyDPServer_GetNUMA_Call struct {
	*mock.Call
}

// GetNUMA is a helper method to define mock.On call
func (_e *MockTopologyDPServer_Expecter) GetNUMA() *MockTopologyDPServer_GetNUMA_Call {
	return &MockTopologyDPServer_GetNUMA_Call{Call: _e.mock.On("GetNUMA")}
}

func (_c *MockTopologyDPServer_GetNUMA_Call) Run(run func()) *MockTopologyDPServer_GetNUMA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTopologyDPServer_GetNUMA_Call) Return(_a0 int) *MockTopologyDPServer_GetNUMA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopologyDPServer_GetNUMA_Call) RunAndReturn(run func() int) *MockTopologyDPServer_GetNUMA_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceName provides a mock function with no fields
func (_m *MockTopologyDPServer) GetResourceName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourceName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTopologyDPServer_GetResourceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceName'
type MockTopologyDPServer_GetResourceName_Call struct {
	*mock.Call
}

// GetResourceName is a helper method to define mock.On call
func (_e *MockTopologyDPServer_Expecter) GetResourceName() *MockTopologyDPServer_GetResourceName_Call {
	return &MockTopologyDPServer_GetResourceName_Call{Call: _e.mock.On("GetResourceName")}
}

func (_c *MockTopologyDPServer_GetResourceName_Call) Run(run func()) *MockTopologyDPServer_GetResourceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTopologyDPServer_GetResourceName_Call) Return(_a0 string) *MockTopologyDPServer_GetResourceName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopologyDPServer_GetResourceName_Call) RunAndReturn(run func() string) *MockTopologyDPServer_GetResourceName_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockTopologyDPServer) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTopologyDPServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTopologyDPServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTopologyDPServer_Expecter) Start(ctx interface{}) *MockTopologyDPServer_Start_Call {
	return &MockTopologyDPServer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockTopologyDPServer_Start_Call) Run(run func(ctx context.Context)) *MockTopologyDPServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTopologyDPServer_Start_Call) Return(_a0 error) *MockTopologyDPServer_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopologyDPServer_Start_Call) RunAndReturn(run func(context.Context) error) *MockTopologyDPServer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockTopologyDPServer) Stop() {
	_m.Called()
}

// MockTopologyDPServer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTopologyDPServer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockTopologyDPServer_Expecter) Stop() *MockTopologyDPServer_Stop_Call {
	return &MockTopologyDPServer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockTopologyDPServer_Stop_Call) Run(run func()) *MockTopologyDPServer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTopologyDPServer_Stop_Call) Return() *MockTopologyDPServer_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTopologyDPServer_Stop_Call) RunAndReturn(run func()) *MockTopologyDPServer_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockTopologyDPServer creates a new instance of MockTopologyDPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopologyDPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopologyDPServer {
	mock := &MockTopologyDPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
