//go:build !ignore_autogenerated

/*
 * Copyright 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeSpec) DeepCopyInto(out *BridgeSpec) {
	*out = *in
	if in.Mtu != nil {
		in, out := &in.Mtu, &out.Mtu
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeSpec.
func (in *BridgeSpec) DeepCopy() *BridgeSpec {
	if in == nil {
		return nil
	}
	out := new(BridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDpdkConfig) DeepCopyInto(out *OvsDpdkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDpdkConfig.
func (in *OvsDpdkConfig) DeepCopy() *OvsDpdkConfig {
	if in == nil {
		return nil
	}
	out := new(OvsDpdkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvsDpdkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDpdkConfigList) DeepCopyInto(out *OvsDpdkConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvsDpdkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDpdkConfigList.
func (in *OvsDpdkConfigList) DeepCopy() *OvsDpdkConfigList {
	if in == nil {
		return nil
	}
	out := new(OvsDpdkConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvsDpdkConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDpdkConfigSpec) DeepCopyInto(out *OvsDpdkConfigSpec) {
	*out = *in
	if in.VhostUser != nil {
		in, out := &in.VhostUser, &out.VhostUser
		*out = new(VhostUserSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDpdkConfigSpec.
func (in *OvsDpdkConfigSpec) DeepCopy() *OvsDpdkConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OvsDpdkConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDpdkResourcePolicy) DeepCopyInto(out *OvsDpdkResourcePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDpdkResourcePolicy.
func (in *OvsDpdkResourcePolicy) DeepCopy() *OvsDpdkResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(OvsDpdkResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvsDpdkResourcePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDpdkResourcePolicyList) DeepCopyInto(out *OvsDpdkResourcePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvsDpdkResourcePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDpdkResourcePolicyList.
func (in *OvsDpdkResourcePolicyList) DeepCopy() *OvsDpdkResourcePolicyList {
	if in == nil {
		return nil
	}
	out := new(OvsDpdkResourcePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvsDpdkResourcePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvsDpdkResourcePolicySpec) DeepCopyInto(out *OvsDpdkResourcePolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Bridges != nil {
		in, out := &in.Bridges, &out.Bridges
		*out = make([]BridgeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvsDpdkResourcePolicySpec.
func (in *OvsDpdkResourcePolicySpec) DeepCopy() *OvsDpdkResourcePolicySpec {
	if in == nil {
		return nil
	}
	out := new(OvsDpdkResourcePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupID.
func (in *UserGroupID) DeepCopy() *UserGroupID {
	if in == nil {
		return nil
	}
	out := new(UserGroupID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VhostUserSpec) DeepCopyInto(out *VhostUserSpec) {
	*out = *in
	in.User.DeepCopyInto(&out.User)
	in.Group.DeepCopyInto(&out.Group)
	if in.SelinuxLabel != nil {
		in, out := &in.SelinuxLabel, &out.SelinuxLabel
		*out = new(string)
		**out = **in
	}
	if in.ACLUsers != nil {
		in, out := &in.ACLUsers, &out.ACLUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VhostUserSpec.
func (in *VhostUserSpec) DeepCopy() *VhostUserSpec {
	if in == nil {
		return nil
	}
	out := new(VhostUserSpec)
	in.DeepCopyInto(out)
	return out
}
